### ISSUE TITLE
Dace-vscode cannot be used with remote SSH

### ISSUE THREAD

**Issue by HappyCockroach** [spcl/dace-vscode#109]
Dace is a great tool for performance engineers, and I really want to learn how to use it.  
But now I have a problem: 
I'm working under Windows and using remote SSH to connect to my Linux server. Dace-vscode has been successfully installed on the Linux server, but it does not work properly.  
<img width="995" alt="startcode" src="https://user-images.githubusercontent.com/80052401/127737613-0fb2a603-29df-4d16-8fd9-560bfcfceea2.png">
![problem](https://user-images.githubusercontent.com/80052401/127737623-a7f8d647-1f4f-4cf3-8520-fb3c062e3bf8.gif)

My remote server's operating system is: x86_64   CentOS Linux release 7.8.2003 (Core)
I installed DACE in anoconda's environment.
Why does dace-vscode not work properly?

**Comment by HappyCockroach** [comment]
This error no longer appears

**Comment by tbennun** [comment]
Thanks. Yes, we resolved the issue in the latest release.
