### ISSUE TITLE
Changing data container types does not update available attributes

### ISSUE THREAD

**Issue by phschaad** [spcl/dace-vscode#156]
When a data container type is changed, the available set of attributes on the container is not updated. This is problematic if the user changes between two container types with largely different attributes, like from a `Scalar` to an `Array`. Any attributes not present in the `Scalar` type will be missing and cannot be added manually to the `Array` type.

This needs to be handled by:
1. Removing any attributes that are not available for the new type
2. Adding any attributes the new type has, which are not present in the old type, by filling them with their default values

**Comment by tbennun** [comment]
This also relates to a future development of properties that have child properties, such as enums with properties (map schedules with extra device-specific details).
