### ISSUE TITLE
Show symbols similarly to arrays in the sidebar

### ISSUE THREAD

**Issue by tbennun** [spcl/dace-vscode#185]
Name and type, editable rather than JSON-formatted.

**Comment by phschaad** [comment]
I want to make sure I don't misunderstand the requiement / feature request here, but is this what was the idea:
![image](https://github.com/spcl/dace-vscode/assets/9193712/4c981e74-142a-470a-ad70-1330a3634fcc)

@tbennun

**Comment by tbennun** [comment]
Yes but the sidebar should be like arrays too
