### ISSUE TITLE
Fix / improve goto source and generated code

### ISSUE THREAD

**Issue by phschaad** [spcl/dace-vscode#197]
Both features are currently unreliable and often don't find the correct files. This is particularly true for remote settings (WSL, containers, SSH)

**Comment by tbennun** [comment]
It seems to be using the root workspace folder as the base path for the generated code, instead of the original file.

**Comment by tbennun** [comment]
Also, jumping to lines would unnecessarily add 1 to the line number. e.g., jumping to line 92 would go to line 93 in the editor
