### ISSUE TITLE
Allow users to specify path for runtime-measurements

### ISSUE THREAD

**Issue by rohanrayan** [spcl/dace-vscode#232]
I am using the VS-code extension for SDFGs using a remote-SSH. This means that I execute my programs on a linux server while the VS code itself is running on my windows machine. In this case, when I want to run an SDFG and get its runtime measurements into the tool, clicking on the "Browse" button opens up a local (windows) file explorer, but the actual measurements are on the linux server.

Is there a way to specify the path of the measurement data on the linux server? Maybe allow users to set a path directly?

Thanks

**Comment by phschaad** [comment]
Thank you for reporting this behavior, this is unintended and we were not aware of this. There is currently no mechanism for circumventing this and forcing it to open the browse feature on the remote, however I will make sure this is addressed. The VSCode API should allow us to open the browse window on the remote - if this is not possible, a workaround (such as the one you point out, directly specifying the path) will be provided.

I have moved the issue to the August milestone.
