### ISSUE TITLE
Code extension ignoring symbol specialization

### ISSUE THREAD

**Issue by rohanrayan** [spcl/dace-vscode#235]
**Describe the bug**
The "inspect access patterns (local view)" tab ignores specialization of matrix dimensions for a simple use-case

**To Reproduce**
1. Generate the SDFG by running the attached python notebook
2. Open the generated SDFG using the VS-Code extension
3. Select the entire SDFG, click on the "inspect access patterns (local view)" button
4. In the pop-ups for M and N, enter 5 and 5 respectively
5. The next tab that opens up shows matrices of much larger dimensions (I presume taken from the python notebook somehow)

**Expected behavior**
I expect the matrix sizes to be specialized to the input dimensions (in this case 5x5)

**Desktop (please complete the following information):**
Dace v0.14.3
VS-Code extension v1.5.7

[vs_code_bug.zip](https://github.com/spcl/dace-vscode/files/12801029/vs_code_bug.zip)

**Comment by rohanrayan** [comment]
Update: This issue seems to be related to https://github.com/spcl/dace/issues/1391

The code extension works if I set the arguments to `A:dace.float64[M, N]` instead of `A=dace.float64[M, N]`

So this issue can be closed in my opinion.

**Comment by phschaad** [comment]
Thank you for the update! I will close it, but feel free to reopen if the issue persists.
