### ISSUE TITLE
Unable to start DaCe backend for v1.5.8

### ISSUE THREAD

**Issue by rohanrayan** [spcl/dace-vscode#238]
The dace backend is unable to start for the latest v1.5.8 release of the code extension (v1.5.7 works). I tried this with dace v0.14.3 and v0.14.4, which didnt help. I get the following error:

rrayan@83:~/dace$ /usr/bin/python /home/rrayan/.vscode-server/extensions/phschaad.sdfv-1.5.8/backend/run_dace.py -p 44235
Traceback (most recent call last):
  File "/home/orr6kor/.vscode-server/extensions/phschaad.sdfv-1.5.8/backend/run_dace.py", line 56, in <module>
    from dace_vscode import work_depth, transformations
  File "/home/orr6kor/.vscode-server/extensions/phschaad.sdfv-1.5.8/backend/dace_vscode/work_depth.py", line 5, in <module>
    from dace.sdfg.work_depth_analysis.work_depth import analyze_sdfg, get_tasklet_work, get_tasklet_work_depth, get_tasklet_avg_par
ModuleNotFoundError: No module named 'dace.sdfg.work_depth_analysis'

**Comment by tbennun** [comment]
Thank you for reporting this. This import will be available in dace v0.15, and it should be optional in v0.14 and below. @phschaad

**Comment by phschaad** [comment]
Thank you! I will make sure to publish a patch for this making the import optional.

**Comment by phschaad** [comment]
A patch has been published (1.5.9) and should be available soon. I hope this fixes the problem, otherwise feel free to reopen the issue.
