### ISSUE TITLE
No "DaCe" in the VSCode marketplace

### ISSUE THREAD

**Issue by mratsim** [spcl/dace-vscode#4]
I tried searching for the extension in VSCode market place with "dace" but did not find it, had to use "sdfg" instead.

DaCe should be in the overview for easier discovery

![image](https://user-images.githubusercontent.com/22738317/83414465-e1f29600-a41d-11ea-8eb4-674fa3d35951.png)

**Comment by tbennun** [comment]
You're right! I thought dace shows up because it's in the description, but it isn't. @phschaad can you add DaCe to the title? Something like:

DaCe SDFG Viewer

**Comment by phschaad** [comment]
Thank you for pointing this out - you're right! DaCe will be added to the title like @tbennun suggested with the next update
