### ISSUE TITLE
Attributes which are null are not listed in an SDFG element's property list

### ISSUE THREAD

**Issue by phschaad** [spcl/dace-vscode#41]
Null attributes should still be listed, but indicated as being null, an empty string, 0, or their respective representation per applicable type.

**Comment by tbennun** [comment]
Is it not an issue with dace-webclient or sdfg_utils.js too?

**Comment by phschaad** [comment]
dace-webclient (or `sdfg_utils.js`) shows "null" if a value is `null` or `undefined`. This behavior is entirely overridden by `sdfv_overrides.js`, introducing this bug, sadly.
